version: '2'
services:
   phpmyadmin:
      image: phpmyadmin/phpmyadmin
      restart: always
      ports:
         - "8080:80"
      environment:
         - PMA_HOST=mysql
      depends_on:
         - mysql
   mysql:
      image: mariadb:10
      restart: always
      ports:
         - "3306:3306"
      environment:
         - MYSQL_ROOT_PASSWORD=1234
      volumes:
         - /data/mariadb:/var/lib/mysql
